#!/bin/sh


colArg=$1


echo "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">"
echo "<html>"
echo "	<head>"
echo "		<title>Pictures</title>"
echo "	</head>"
echo "	<body>"
echo "		<h1>Pictures</h1>"
echo ""

dirArg=$2
lastRow=false
endRow=false
if [ $colArg -gt 0 ] ; then
	for j in $(find $2 -type d -name '[0-9][0-9][0-9][0-9]')
	do
		year=${j: -4}
		echo "<h2>$year</h2>"
		echo "<table>"
		colNum=0
		for i in $j/[0-9][0-9]/*.jpg
		do
			# if there are arguments
			if [ $colNum -eq 0 ] ; then
				echo "	<tr>"
				endRow=true
			fi
				echo "		<td><img=\"$i\" height=100></td>"
				colNum=$((colNum+1))
			if [ $colNum -eq $colArg ] ; then
				echo "	</tr>"
				colNum=0
				endRow=false
			fi
		done
		while [ $colNum -ne $colArg ] && [ "$endRow" = true ]
		do
			lastRow=true
			echo "		<td></td>"
			colNum=$((colNum+1))
		done
		if [ "$lastRow" = true ] ; then
			echo "	</tr>"
			lastRow=false
		fi
		echo "</table>"
	done
fi
echo "</body> </html>"

