#!/bin/sh


colArg=$1
shift
picsAmount=$#

echo "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">"
echo "<html>"
echo "	<head>"
echo "		<title>Pictures</title>"
echo "	</head>"
echo "	<body>"
echo "		<h1>Pictures</h1>"
echo ""

echo "<table>"
# if there are arguments
while [ $picsAmount -gt 0 ] && [ $colArg -ne 0 ]
do
	# if the file is not a jpeg
	#if [ ! file $i | grep -q JPEG ] ; then
	#	echo "Invalid file">&2; exit 1
	#else
	echo "	<tr>"
	colNum=0
	while [ $colNum -lt $colArg ]
	do
		if [ $# -gt 0 ] ; then
			if `file $1 | grep -q JPEG ` ; then
				echo "		<td><img src=\"$1\" height=100></td>"
				shift
				picsAmount=$((picsAmount-1))
				colNum=$((colNum+1))
			else
				echo "$1 Invalid file argument">&2; exit 1
			fi
		else
			echo "		<td></td>"
			#shift
			colNum=$((colNum+1))
		fi
	done
	# fi
	echo "	</tr>"
done
echo "</table>"
echo "</body> </html>"
